Repository meething/meething, pull requests merged in 2020-06, with the labels that each got.

#197 Update modal.js - fixes undefined I believe
  src/assets/js/modal.js
Labels: bug

#185 Make sure to take the first remote screen
  src/assets/js/ui/pipmode.js
Labels: TOWNHALL, bug

#196 Add screenshare identifier
  src/assets/js/sfu/sfu.js
Labels: TOWNHALL, enhancement

#198 Start muted
  src/assets/js/sfu/sfu.js
  src/assets/js/sfu/video.js
Labels: TOWNHALL

#199 Standard 75% of volume on when active speakers talks 100%
  src/assets/js/helpers.js
Labels: TOWNHALL

#200 help text for /share command
  src/assets/js/chat.js
Labels: TOWNHALL

#235 Make stuff not break when using helpers
  src/assets/js/helpers.js
Labels: FRONTEND

#227 Add video recording for active speaker
  src/assets/js/helpers.js
  src/assets/js/ui/pipmode.js
  src/index.html
Labels: FRONTEND, enhancement
