Repository meething/meething, pull requests merged in 2020-05, with the labels that each got.

#110 Ux tingle modal
  src/assets/css/app.css
  src/assets/css/bootstrap.min.css
  src/assets/css/tingle.css
  src/assets/js/config.js
  src/assets/js/dragable.js
  src/assets/js/ee.js
  src/assets/js/emitter.js
  src/assets/js/encoding-indexes.js
  src/assets/js/encoding.js
  src/assets/js/events.js
  src/assets/js/helpers.js
  src/assets/js/metadata.js
  src/assets/js/presence.js
  src/assets/js/rtc.js
  src/assets/js/tingle.js
  src/assets/video/muted.mp4
  src/assets/video/muted.ogg
  src/assets/video/muted.webm
  src/index.html
Labels: BACKEND, FRONTEND, bug

#108 Fix audio recording
  src/assets/js/helpers.js
  src/assets/js/rtc.js
Labels: bug

#100 WIP PR Graph
  src/assets/js/graphThing.js
  src/assets/js/rtc.js
  src/assets/workers/workerGraph.js
  src/index.html
Labels: FRONTEND, enhancement

#127 UI-Ux update
  src/assets/css/app.css
  src/assets/css/dragable.css
  src/assets/css/snackbar.css
  src/assets/css/tingle.css
  src/assets/js/events.js
  src/assets/js/rtc.js
  src/assets/js/tingle.js
  src/index.html
Labels: FRONTEND, enhancement

#151 Chat fix
  src/assets/css/app.css
  src/assets/js/chat.js
  src/assets/js/connection.js
  src/assets/js/main.js
  src/assets/js/metadata.js
  src/assets/js/modal.js
  src/assets/js/sfu/room.js
  src/assets/js/uex.js
  src/index.html
Labels: beforefridayfix

#140 UEX.js split out dom.listeners into it's own module
  src/assets/js/chat.js
  src/assets/js/main.js
  src/assets/js/modal.js
  src/assets/js/sfu/room.js
  src/assets/js/uex.js
  src/index.html
Labels: enhancement

#171 Add PiP mode for active speaker changing
  src/assets/js/connection.js
  src/assets/js/helpers.js
  src/assets/js/main.js
  src/assets/js/ui/pipmode.js
  src/assets/js/ui/toggles.js
  src/index.html
Labels: FRONTEND, enhancement
